add_newline = false
continuation_prompt = "[󰞷](dimmed white)[](bold dimmed white)[](bold dimmed magenta)[󰅂](bold dimmed blue)"

right_format = """
"""

[character]
success_symbol = "[](bold dimmed white)[](bold white)[](bold magenta)[󰅂](bold blue)"
error_symbol = "[](bold dimmed white)[](bold white)[](bold magenta)[](bold red)"

[package]
disabled = true

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""
style = "bold megenta"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ PICKING](bold red)"

[cmd_duration]
disabled = false
format = '[$duration](bold magenta) [󰅒](bold blue)'

[git_status]
conflicted = ""
ahead = " "
behind = " "
diverged = "󰨁 "
untracked = "[](yellow) "
stashed = "󰆼 "
modified = " "
staged = '[ \($count\)](green) '
renamed = " "
deleted = " "
style = "bold purple"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format =  "on [$hostname](bold cyan) "
trim_at = ".localdomain"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '[](blue) [$time](dimmed blue) '
time_format = "%T"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"

[rust]
symbol = ""
format = "via [$symbol ($version)](bold red) "

[nodejs]
symbol = "󰎙"
format = "via [$symbol](bold green) "

[bun]
symbol = ""
format = "via [$symbol ($version)](bold white) "

[dart]
symbol = ""
format = "via [$symbol ($version)](bold sky) "

[python]
symbol = ""
format = "via [$symbol ($version)](bold green) "

[java]
symbol = ""
format = "via [$symbol ($version)](bold white) "

[kotlin]
symbol = ""
format = "via [$symbol ($version)](bold blue) "

[gradle]
symbol = ""
format = "via [$symbol ($version)](bold cyan) "

[php]
symbol = ""
format = "via [$symbol ($version)](bold blue) "

[zig]
symbol = ""
format = "via [$symbol ($version)](bold yellow) "
